### ISSUE TITLE
Need ability to store and save connection objects

### ISSUE THREAD

**Issue by lokedhs** [K1D77A/lunamech-matrix-api#1]
Consider a UI client using the API. The user logs in by creating a connection object with username and password, and then calling an authentication function such as `PASSWORD-LOGIN` to authenticate the connection.

At some point, one needs to be able to store the token in a configuration file that can be read when the application restarts. Thus, there needs to be a way to serialise a connection object so that it can be written to a file, and later loaded again and have the connection object recreated.

It may be possible to recreate the connection object using only the token. In that case, no serialisation function is needed, but there must still be a way to create a connection using only the token.

**Comment by K1D77A** [comment]
No problem, I will implement this and put it into v1.
