### ISSUE TITLE
change sb-ext:timeout to bt:timeout for othe rimplementaions

### ISSUE THREAD

**Issue by Yehouda** [K1D77A/lunamech-matrix-api#4]
https://github.com/K1D77A/lunamech-matrix-api/blob/d17183b4e9f61f8fdc4001a2af137bdcd4de1a86/api/api-helpers.lisp#L79

The **bt:with-timeout** signals **bt:timeout**, so that is what this code should use. 

On SBCL **bt:timeout** is deftyped to **sb-ext:timeout**, so that will still work on SBCL.

**Comment by K1D77A** [comment]
Done
